### ISSUE TITLE
Relative difference error

### ISSUE THREAD

**Issue by takerujason** [ChengBinJin/MRGAN-TensorFlow#1]
Hi @ChengBinJin ,
There is a question about paper and README. How to print the relative difference error like figure 7 in paper and README. Could you provide the code or guidance? 

![](https://user-images.githubusercontent.com/37034031/64340046-39470f80-d020-11e9-8e2b-9e44cb78f117.jpg)

Sorry for this silly question. I'm a beginner in this field. Thanks a lot!

**Comment by ChengBinJin** [comment]
@JCFu 
I would like to provide an example code. You can revise the following codes for your own data.
```
import cv2
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.axes_grid1 import make_axes_locatable

# original input img (assume)
src = cv2.imread('lena.png', cv2.IMREAD_GRAYSCALE)

# predicted result (assume)
kernel = np.ones((15, 15), np.float32) / (15 * 15)
dst = cv2.filter2D(src, ddepth=-1, kernel=kernel)

# calculate relative error
relative_img = np.abs(src - dst).astype(np.uint8) / src


imgs = [src, dst, relative_img]
titles = ['Input', 'Prediction', 'Relative error']
fig, axes = plt.subplots(ncols=3)

for i, img in enumerate(imgs):
    if i != len(imgs) - 1:
        img_ = axes[i].imshow(img, cmap='gray')

    else:
        img_ = axes[i].imshow(img, cmap='autumn')

        divider = make_axes_locatable(axes[i])
        cax = divider.append_axes("right", size="5%", pad=0.05)
        fig.colorbar(img_, cax=cax)

    axes[i].set_title(titles[i])
    axes[i].set_xticks([])
    axes[i].set_yticks([])

plt.tight_layout(h_pad=1)
plt.show()
```

Run the above code you can show the figure like this.
![test](https://user-images.githubusercontent.com/37034031/70873090-4c8a5380-1fef-11ea-9413-b28f25c17b3c.png)

**Comment by takerujason** [comment]
@ChengBinJin 
Thank you for your warm-hearted answer!
